### ISSUE TITLE
[tracker] AuxPoW <-> BIP9 Compatibility

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1340]
This is a tracking issue for making AuxPoW compatible with BIP9. See #1334 for a problem description.

### To decide
- [ ] whether to hard-fork on block height or date
- [ ] agree on a height/date for the hard-fork

### Milestone: BETA-1
- [ ] remove `CBlockVersion` and re-implement logic inside `CBlock` => #1339
- [ ] make the built-in miner mine a virtual parent chain
- [ ] remove `getblocktemplate` rpc call
- [ ] v4 soft-fork to become AuxPoW-only, introduce chainId inside `CBlock.nNonce`
- [ ] backport soft-fork status report RPC call from Bitcoin

### Milestone: BETA-2
- [ ] conditional hard-fork based on v4 soft-fork that removes the `nVersion` abuse and "Aux POW parent cannot have our chain ID" constraint.
- [ ] command-line argument allowing node operators to enforce protocol version post-hard-fork (to not get eclipsed with traffic from non-updated nodes.)

### Milestone: RC-1
- [ ] backport CLTV into a v5 soft-fork
- [ ] command-line argument allowing miners to explicitly not mine v5.

### Non-committed / optional
- [ ] integration test script over different releases, to do qa on the forks

If I forgot anything, feel free to suggest :-)

**Comment by patricklodder** [comment]
Added prerequisite of tagging and releasing `alpha-1`, to have a clear mark before deep fork changes

**Comment by patricklodder** [comment]
I've removed CLTV to make this plan more atomic. We can softfork for CLTV later.

**Comment by ummjackson** [comment]
@patricklodder What's the latest on this? We need to have this conversation as Litecoin are activating segwit and I don't have confirmation (yet) about how they plan to. If they use BIP-9 then I believe we're going to have a problem?

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Jackson Palmer:
> @patricklodder What's the latest on this? We need to have this
> conversation as Litecoin are activating segwit and I don't have
> confirmation (yet) about how they plan to. If they use BIP-9 then I
> believe we're going to have a problem?

My understanding is that as long as Litecoin isn't using a BIP9 bit
that Dogecoin thinks is the AuxPoW bit, and as long as the top 16 bits
of Litecoin's nVersion don't look like the Dogecoin chain ID, whatever
Litecoin does won't harm Dogecoin.  By far the bigger problem is if
Dogecoin tries to do a softfork using BIP9.

Bitcoin has already done one BIP9 softfork, and Namecoin wasn't
affected due to neither of the above scenarios occurring.  However,
Namecoin can't activate that softfork until we hardfork to fix BIP9
compatibility.

(Disclaimer: I'm not an expert on what Dogecoin and Litecoin have done
differently from Namecoin and Bitcoin, and Daniel Kraft is the expert
on the Namecoin issue here.  So, any of the above could plausibly be
mistaken.)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZD/q/AAoJELPy0WV4bWVwexQP/AzSkK3O1NE9Tyx2uHlu5QAm
SD/rCAc9gmVMavYT16FeD590YK7vwA0aVrCsDdSZT67q7g74vS5S+0hZu/dtVGoJ
B2DjGAhe02C2P0EmJ+csIyjisVm4HOlVn00wgQz7fiFuhddEBkjJM7Wx8qqwHudP
b6NklDFGa313lL6Q+C7XohQBFgTOYnDxIgNP+5C7rDEUl6x3kTo8BNKTtmSw1/3h
FX6ry+BPMWDyTZrKI989XypyQvcCuy/EjDVRlkH982bBSS8MGnDP2Gvn8zq8dZu4
W574TBOC5TfhgHBhMVG1VCZYItQoqEzpol9U6sg5X9QYZ+2+XN1F7YNbPU1btEhp
th5e+/m50BZs3MBw0PspLVAZLniBB1eaS607DkfGG+/8baideIbCIkYBW27zieZw
UQwvabf7Cr7selIprhkFEPwjsxBzVWgmb6u7y36vLzMP6CWXcuQPlp3S9Hlh+6rU
hG9EePVKsn6metId+P5mXa3x3C/vvlOH+IZUvk3sgypFu2KheroKuy5wv129CyHn
Vb4CV1JxIT28R3CUBXzW8bXJXndytQtFCpv+pBxt9P522SpSQRxXJ9eY7jkFh4Fl
UChI8pFctYlk3nB8SXTvtgRI7N/f28VwblBcc5YMZcP08TtfRMIF7WsM2HIop0LU
SVtmuPGM/alYnwAdBSZA
=My/O
-----END PGP SIGNATURE-----

**Comment by langerhans** [comment]
Just to chime in, I've talked about it with @rnicoll too and we came to the same conclusion as you @JeremyRand. Also given our chainId is 0x62 we'd have an even harder time hitting the above conditions than Namecoin has if I understand the issue correctly with their chainId being 0x1.

**Comment by patricklodder** [comment]
@ummjackson : same state as is documented here in the task progress.
@langerhans : did you guys already walk through the validation steps? I'd have to look into if we do things like `(version & 0x62) == true` or `(version & 0x62) == 0x62` as that kind of matters towards whether it's harder or easier to hit the scenario. If you didn't then I'll do an analysis this week.

**Comment by rnicoll** [comment]
@patricklodder I've not built a test case yes, which yes ideally we should.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

If I understand correctly (and I might not, this is something I was
told in IRC long ago), BIP9-compliant nVersion fields always set the
highest bit to 1.  So since the highest bit of 0x0062 isn't 1 (nor is
the highest bit of 0x0001, which is Namecoin's chain ID), I don't
think the failure mode of Litecoin nVersion appearing to have the
Dogecoin chain ID is possible.  (The AuxPoW bit being used by Litecoin
nVersion is a possible failure mode still.)

(Please verify this by checking the BIP9 spec or something, don't take
my word for it.)

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZEQaeAAoJELPy0WV4bWVwgYwP/2lewysw1zDYGK9MimqAePuC
HL7no5CNxCSAFMVMXaAxkMfYcU7St86dUXYSTlwMfd/JGvDdu7RAD0HEMEzaBL1X
0ZOBNMpQs657TkYM1o1wjNES7msK5nNuqpNXvcforOTFdJGEsCercYNDZG0JLvD1
Rq9TfL1PXd4BK5YCEnbGbo1jajGnihaKIvjaEzUIm0nzy4IxDR5NsmDyU/JiLPPo
G0LjJfAB2fbgEj5MdnkVw8gKsU5K0RWGWqI74sxLaxQjcU15rDMpO3HtWTl6LfAB
o/b8JslPUxQjJoYogVkHK8xvA9Uqy4JNwp15t0a6un5nNqF9MXSqQGRJ0yx/4iCD
XSQECBKM8GH/g6T0g6zG/J4ZnOfCfQvLWxCZWwOgLGInCYotmFPCeY6AJgVE+Phn
7hfnWyB6fD8BW4qdNfy4eLWuY+RkPK+1J6FzR+edAnxyLd6U6qNQBm8H+niuWaib
L6IiQvNTzoS6BiO5NITSDjdzxML2U6AXSIwbNN5oOrjTWi5w64q5rGVURhHX9XsZ
KYeAJOmlS/GLGhlNwYvVAWWEa87I4r5fy/MmYG8ixO8jgQY3A4OzWmmyy540gl2S
19GKDfA74acEL0ppbhChvZBmQGQ48C9y+Mjvfz6lfEfEn5nVavqe1w+0vbljlg1k
OVJD3UDv3aYh+Ek1LYHm
=XMWQ
-----END PGP SIGNATURE-----

**Comment by rnicoll** [comment]
Considering if we can simplifying a bit:

* Dogecoin Core 1.18 would introduce a new block version (v5), which is always-AuxPoW, sets the chain ID as before (so it _looks_ like a softfork), enables SegWit on supermajority.
* Dogecoin Core 1.20/1.21 would then encode SegWit activation height as when the V5 supermajority kicked in, at which point from our perspective it's not an ongoing maintenance pain.
* BIP9 version bit for SegWit is never used on Dogecoin
* If we want BIP9 later, it's a new (V6) block, which makes the v5 fork a hard fork. The hope is this is far enough in the future that the few people left behind are a minor subset.

**Comment by patricklodder** [comment]
Agreed. Parking this is for now the best option we have.
