### ISSUE TITLE
Docs4Doge Initiative - Update the Dogecoin documentation

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2271]
Documentation is fundamental to use a software & to build an open source project.

The Dogecoin documentation need a major update : documents are outdated, it lacks information, it's messy.

Work is needed for developers, users and contributors documentation.
Many devs struggle to start, many users face an unfamiliar world, many contributors' willingness is not catalyzed.

Improving the documentation is a way to participate in the rise of Dogecoin.

## Goal of the issue

This issue is here (to try) **to impulse a dynamic to work on the documentation** and **to define collaboratively a roadmap**.

This is a place to centralize information, do not hesitate to link here to a new issue for related subtopics.

## Potential impacts

Documentation could serve different purposes :
- Easier use of Dogecoin Core
- Increase developers/contributors/code reviewer base
- Reduce entry barrier, reduce contributor struggle
- Improve contribution quality
- Improve project communication
- Interact more with the blockchain ecosystem
- More educated dev/user/contributor base
- Stimulate collaboration & community projects
- Better information management
- ...

## Roadmap [Work in progress, will be updated regularly]

As a first draft, I suggest this roadmap. It's a work base to improve.
Some points could be controversial & must be discussed before acting.

#### Common to the entire documentation

- [x] Explain/display list of communication tools
- [ ] Remove duplicate & possible irrelevant content
- [x] Create separate FAQ.md
- [ ] Add answer to "can we limit the cap ?"
- [ ] Add table of content on some page where useful
- [ ] Localization (possibly tricky)
- [ ] Define code of conduct
- [ ] Link to other repo (dogecoin.com/rosetta/whatever)
- [ ] Link to community projects (see #2430)

#### Developer documentation

- [ ] Refresh build guides
  -  [x] Refresh unix #2465 
  -  [ ] Refresh OSX
  -  [ ] Refresh Windows
- [ ] RPC API documentation
- [x] Basic guide for dogecoind (#2568)
- [x] Basic guide for dogecoin-cli (#2568)
- [ ] Basic guide for dogecoin-tx
- [x] Basic guide for configuration (#2568)
- [ ] Update [gitian process](https://github.com/dogecoin/dogecoin/blob/master/doc/gitian-building.md) #2579
- [ ] Add docker implementation (PR #2337 & issues #2250/#2195)
- [ ] Info about Dogecoin Improvement Proposals ([DIPs](https://github.com/dogecoin/dips))

#### Contributor documentation

- [x] Add explicitly "help wanted"/"good first issue" issues/PR. See #2170.
- [ ] Contributing guidelines for non-dev
- [ ] Update issue rules (#2110 & #2191)
- [ ] Add credit file

#### User documentation

I do not write anything here, but I think we should start to think about it.
Users are hodlers, they do not have real docs about how to use Dogecoin & how it works.

In the idea where Dogecoin is an entry point to cryptos, it would be great to give educational resources through some docs.
I don't know if it should belong to this repo or another ([dogecoin.com](https://github.com/dogecoin/dogecoin.com) ?).

## Contribute to Docs4Doge !

This roadmap is suggested areas for documentation improvement, it's open to discuss & can evolve !
So, at first, you're encouraged to suggest ideas & discuss the initiative, report any issues with docs :heart:.

You can help on roadmap links, which are all [issues](https://github.com/dogecoin/dogecoin/issues?q=is%3Aissue+is%3Aopen+docs4doge) and [pull requests](https://github.com/dogecoin/dogecoin/pulls?q=is%3Apr+is%3Aopen+docs4doge) related to the initiative. Your code reviews and feedbacks are helpful :rocket:

Feel free to start working on any item of the roadmap, any area of the documentation where you can and want to help.
Check if no one else is working on it, let us know in case someone might help and/or start a piece of code and share a nice pull request !

Let's chat using issues, [GitHub Discussion](https://github.com/dogecoin/dogecoin/discussions), or [#-core-dev](https://discord.gg/dogecoin) channel on discord.

**Comment by patricklodder** [comment]
> Recruit Vitalik Buterin & Charles Hoskinson

???

**Comment by Paddy613** [comment]
****

**Comment by AbcSxyZ** [comment]
@patricklodder If they are able to see what's going on, because they already took time to improve dogecoin, suggest collab, who knows what could happen :rofl: !

And if it's not them, it could be some other blockchain developers 😉

**Comment by patricklodder** [comment]
So, I'd recommend limiting your goals a bit and taking it a few at a time. Gives people a chance to familiarize themselves with what's there too. What's the most urgent item under your "impact" list? And what is the most beneficial long-term?

**Comment by AbcSxyZ** [comment]
> I'd recommend limiting your goals a bit and taking it a few at a time

Idk what is the good balance, having enough tasks could be interesting to involve people & share some work. If it's big enough, I'm telling myself that people are more likely to help.

Some points could be really tricky (localization/architectural overview), and I do not have the technical skills to do all of my suggestions, but a good part is composed of relatively small tasks.

About expected impacts, it somehow already sorted by priority from my pov. But I won't have an opinion if I need for example to choose to focus on educate community members or interact with the blockchain ecosystem. Both have equal importance for me, it will depend on the context.

**Comment by pjhwa** [comment]
For Korean localization, I would like to contribute. :-)

**Comment by AbcSxyZ** [comment]
@pjhwa Depending on the evolution, help for translation would be appreciated :) It would be important to achieve this internationalization.

In the current state, as you did, there is only translation for `dogecoin-qt`, and they started to translate README.md to a single language.
For the rest of the documentation, no tool are used, and to handle all translated files I've no idea how to achieve that. Control evolution, change, allow user to contribute easily, file organization, etc.

No idea when translation work  [on doc] could start, but it can take time. Personally, I will focus on documentation to get started with `dogecoind`, `dogecoin-qt` & cie, hoping more people will come to help !

**Comment by pjhwa** [comment]
@AbcSxyZ Thank you for your contribution and effort on Documentation.

I think we can create country code(i.e., en, ko, and zh, etc.) directories for i18n under [doc] directory and manage it. Before that, it might be good to translate by adding the country code to the file like README-kr.md.

For #2313 , the review is still required but I think I can translate these documents into Korean based on your work.

**Comment by AbcSxyZ** [comment]
Create a country code directory would be a simple way, but I think it will be hard to manage, at least to track change/evolution and keep relatively up-to-date doc for hundreds to thousands of translated files.  
There is probably some existing software/method to achieve that more properly, I doubt [for the middle/long term] it is a good way, someone needs to focus on the topic.

In any case, I think it will be too early to start any translation work on docs. Previous one have a lot of outdated content, and the new docs will probably have a lot of change these next period, would be interesting to have a more stable version to avoid wasting translator's time with regular major changes. Translate PR is definitively too precocious 😉

I would like to help you to contribute on documentation i18n, but right now I'm personally not able to do it... Too early !

**Comment by patricklodder** [comment]
I have been thinking about this effort a bit and was wondering, maybe it's better to make this a separate project, like [Operation Such Frensly](https://github.com/dogecoin/dogecoin/projects/5), rather than binding this to particular releases?

Thoughts?

**Comment by lee5378** [comment]
@AbcSxyZ I'd like to be a part of the effort to improve documentation. 
@patricklodder That seems fair, like a dedicated docs4doge branch that only features documentation changes?

**Comment by AbcSxyZ** [comment]
@patricklodder I don't know where it should go, and it can go far beyond the next release. It would be great to have an update of almost the entire documentation, and it can move pretty far if we start to go for user, miner, blockchain developers, whatever docs.

It's like trying to give some life to the documentation :smile:. As this is (or should be) a constantly evolving process.

**I would love to make something accessible and understandable enough for the community to be somehow autonomous.**

P.S. : @lee5378 I updated the contribute section of my first comment, hope this help you find a way to contribute :)

**Comment by AbcSxyZ** [comment]
## 14/09 Initiative Update

The beginning of this initiative focused on improving the software accessibility from installation to utilization, and give information about used tools by the community to build Dogecoin Core to inform about current development and to let people reach each other.

Refresh the main `README.md` to redirect users inside the software documentation & the open source ecosystem, update the build instructions for Unix and add a Dockerfile to facilitate the Dogecoin Core installation, adding a getting started section to start playing programmatically with Dogecoin.

Hope it will be a nice improvement to help blockchain developers dive in and build amazing apps with Dogecoin integrated !

#### Merged PRs
- https://github.com/dogecoin/dogecoin/pull/2466
- https://github.com/dogecoin/dogecoin/pull/2465

#### Open PRs
- https://github.com/dogecoin/dogecoin/pull/2568
- https://github.com/dogecoin/dogecoin/pull/2337
- https://github.com/dogecoin/dogecoin/pull/2570
- https://github.com/dogecoin/dogecoin/pull/2473
