### ISSUE TITLE
[bug] Dust outputs are always interpreted as non-standard on mainnet

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2603]
# Bug Report

_Follow-up from https://github.com/dogecoin/dogecoin/issues/2601#issuecomment-935062141_

Since v1.14.2, any transaction with an output under 1 DOGE is considered non-standard. 

### What happened?

Historically, from v1.3.0 until v1.8.3, [dogecoin had no dust limit](https://github.com/dogecoin/dogecoin/blob/f626f8f43672a940c7840577b007f3d0010c2179/src/test/transaction_tests.cpp#L3200), but only [a dust penalty](https://github.com/dogecoin/dogecoin/blob/f626f8f43672a940c7840577b007f3d0010c2179/src/main.cpp#L841-L845), that made the creation of dust outputs uneconomical. With 1.10.0, the [test to make sure that a 1 Koinu output isn't dust was not implemented](https://github.com/dogecoin/dogecoin/commit/ce196a9bfc2007b4ce79a1ec874c18fdda453caa#diff-cc0c6a9039a1c9fe38b8a21fe28391fffbac9b8531dfda0f658919a9f74b46baR343-R345), and this change was 1-on-1 [merged onto 1.14.0 later](https://github.com/dogecoin/dogecoin/pull/1587).

When subsequently, v1.14.2 [introduced a 1 DOGE dust limit](https://github.com/dogecoin/dogecoin/commit/388fb79a3a78eae092c57e04c5a816697e14997d), the original test wasn't triggered when the behavior changed, because it was no longer part of the codebase. Even though [code was written](https://github.com/dogecoin/dogecoin/blob/0b46a40ed125d7bf4b5a485b91350bc8bdc48fc8/src/dogecoin.cpp#L179-L188)  to retain the original penalty, the mempool code rejects any transaction with a dust output before any penalties through fees are evaluated, on mainnet. On testnet and regtest, dust transactions will be accepted unless the node explicitly opts out of non-standard transactions, causing both regression and manual testing to not spot this.

### Current behavior

On mainnet only, default configured nodes will not accept any dust output to mempool.

https://github.com/dogecoin/dogecoin/blob/4c93783ab64ba96e60b7ea37202c072c66f3f544/src/validation.cpp#L634-L635

which evaluates dust as non-standard as a policy, per

https://github.com/dogecoin/dogecoin/blob/4c93783ab64ba96e60b7ea37202c072c66f3f544/src/policy/policy.cpp#L108-L111

### Expected behavior

With a default configuration, at least some facility for economically disincentivized dust outputs is available, to allow for future changes to the dust limit.

### Dogecoin Core versions affected

Dogecoin Core v1.14.2, v1.14.3 and v1.14.4

### Proposed path forward

Changes need to be made, preferably within the 1.14.5 release milestone, to restore flexibility in the dust handling, including tests. This does not have to be a long winded process, but it needs to be done with care and precision.

**Proposed changes:**
- [x] Decouple dust limits implemented by the wallet and the relay logic, making sure that by default the wallet sends standard transactions per the 1.14.2 - 1.14.4 definition (for now) regardless of the dust limit used for the mempool: [#2606](https://github.com/dogecoin/dogecoin/pull/2606)
- [x] Make the dust limit for the wallet configurable, to prevent future release lock-in: [#2606](https://github.com/dogecoin/dogecoin/pull/2606)
- [x] Rework the wallet's change policies to be capable of using configurable dust limits, to further improve operator sovereignty: [#2608](https://github.com/dogecoin/dogecoin/pull/2608)
- [x] Rework the mempool parametrization / logic to have both a (configurable!) soft and a hard dust limit, like we had before: [#2606](https://github.com/dogecoin/dogecoin/pull/2606)
- [x] Rework the automated tests that touch fee policy and extend coverage, also for the "unhappy" scenarios, and make sure that node configurations are reflecting mainnet when testing policy implementation: [#2616](https://github.com/dogecoin/dogecoin/pull/2616)
- [x] Change the relay penalty to be the soft dust limit itself, not the relay fee (this was an additional finding when testing alternatives, [see below](https://github.com/dogecoin/dogecoin/issues/2603#issuecomment-938774519)) as otherwise there is no full disincentive: [#2612](https://github.com/dogecoin/dogecoin/pull/2612)
- [x] Change the high tx fee warning threshold (`HIGH_TX_FEE_PER_KB`) to not be lower than any fees recommended by the wallet:  [#2609](https://github.com/dogecoin/dogecoin/pull/2609)

**Proposed default values:**
- Mempool default soft dust limit (under which additional fee needs to be added): `0.01 DOGE` - the same as the recommended fee rate per Kb, to keep things simple and in line with the fee plan.
- Mempool default hard dust limit (under which transactions become non-standard): `0.001 DOGE` - the same as the default minimum relay fee, as this gives plenty of space for growth towards the future.
- Wallet default (hard) limit: `1.00 DOGE` to stay compliant with the current relay network, for the time being. This can in a later release be changed to reflect the soft dust limit when the new rules have been widely adopted by relay nodes and miners.
- High tx fee warning threshold: `10.0 DOGE` because the wallet implements hardcoded fees of ~ 1.02 (`MIN_CHANGE`) and 5.21 DOGE and should not warn on normal operations.

**Comment by victorsk2019** [comment]
> > Would it not then treat dust outputs as standard and resolve the issue?
> 
> It could offer an alternative to the second bullet point of my proposed default hard dust limit: it basically means that being 0. Why would you want that, other than it being a quick hack (because quick hacks is what got us here, so I'd like to know why you think that's a good idea)

Well, I generally try to follow KISS principle as much as possible 😜 and based on the problem description (and my current level of understanding of this subject) I think this could be solution to the issue (if it works, why not?).

**Comment by patricklodder** [comment]
> Well, I generally try to follow KISS principle as much as possible 😜 and based on the problem description (and my current level of understanding of this subject) I think this could be solution to the issue (if it works, why not?).

I'm okay with KISS principle as long as there are tests and documentation, and it's not used as an excuse to cut corners. Do realize that small hacks can have big consequences: I'm really not sure at all if #1615 intended to do this policy change, or that it was accidental, making it a prime example of a case where KISS may be a bit too lazy, and instead doing more research and engineering effort is required for the long-term benefits of the chain and coin. I'm not entirely sure if this is a bug or a feature and it deeply worries me that I had to find this out by writing completely new test scripts. 

However, what I meant with my question was: ***If we want to have no hard dust limit at all, then that should be a conscious decision, because that's a policy reversal, even if the policy was in itself unintended***; it has been a fact for nearly 2 years now. 

I think we should have a broader discussion than just you and I before doing any full policy reversals - going from a 1 DOGE hard dust limit to no hard limit at all is after all a big change. At the very least we need a better idea of what this does, some rationale why that outcome is good, and preferably also validation of that idea being something that the community would see as a good solution.

> It will not cause this block be evaluated in validation.cpp if true:

That said, I [ran a test of your proposed change](https://github.com/patricklodder/dogecoin/blob/b9b897b887aa6c974854319c4430140983ff4dc0/qa/rpc-tests/p2p-policy.py) by simulating this without the `-acceptnonstdtxn=0` and because the minimum relay fee is used instead of the dust limit itself as a penalty, the economic disincentive only will apply fully to outputs lower than 0.001 DOGE instead of 0.01 DOGE. So what you're effectively proposing under current parametrization is:

1. An economically unviable output under 0.001 DOGE - which is 10x lower than what I'm proposing
2. A slightly penalized output under 0.01 DOGE - which would be a new policy
3. No rejection from the network as long as the 0.001 DOGE penalty is paid, not even on 0.00000001 DOGE

I'm not at all confident that that would offer sufficient spam protection - 0.001 DOGE feels low to me as a default and I am not at all sure about there being no rejection at all. Does anyone have any thoughts on this? Please share.

**Comment by victorsk2019** [comment]
Thank you for your feedback and detailed explanation.

`An economically unviable output under 0.001 DOGE - which is 10x lower than what I'm proposing`

I thought maybe `-mintxfee` setting could be used as a limit to dust output?  Same as it works to correct `-paytxfee` fee as per discussion here: https://github.com/dogecoin/dogecoin/pull/2446?

**Comment by patricklodder** [comment]
Further research while I was looking if there would be something to cherry-pick from bitcoin/bitcoin got me to f4d00e63, which is currently part of 1.21-dev. Although that uses a rate in coin/Kb rather than a fixed amount - so it doesn't make sense to cherry-pick that because that would change the method for handling dust completely - we can definitely reuse the terminology of `discard` for the wallet dust limit as that both neatly describes what it does and would not introduce significantly different terminology between 1.14 and 1.21. 

I'll use that terminology for now, but can of course change it if there are objections.

**Comment by patricklodder** [comment]
Implementation has been done, PRs have been reviewed and merged. I'm doing manual testing and will try to propose some cleanup now based on the current 1.14.5-dev

**Comment by kitcateleven** [comment]
Thanks for your hard work everyone. There's a lot to study re: the economics of these decisions - I have a lot to learn but appreciate what you're doing
