### ISSUE TITLE
[Backport] Backports from Bitcoin

### ISSUE THREAD

**Issue by CharesFang** [dogecoin/dogecoin#2744]
We recently investigated the Bitcoin issues which are related to privacy protection, vulnerability patches, or security enhancements. We have also checked the `dgecoin` source code. Results show that these issues and their PRs are not backported yet. Henceforth, we suggest that `dogecoin` should backport the PRs listed below for the considerations of software security and integrity. 

- [ ] Bitcoin [PR#17906](https://github.com/bitcoin/bitcoin/pull/17906), avoid uninitialized reads.
- [ ] Bitcoin [PR#16572](https://github.com/bitcoin/bitcoin/pull/16572), fix a `Char` variable used as `Bool`.
- [ ] Bitcoin [PR#16251](https://github.com/bitcoin/bitcoin/pull/16251), improve `signrawtransacAtion` error reporting.
- [ ] Bitcoin [PR#15305](https://github.com/bitcoin/bitcoin/pull/15305), fix crash when disconnecting fail.
- [ ] Bitcoin [PR#15039](https://github.com/bitcoin/bitcoin/pull/15039), avoid leaking `nLockTime` fingerprint.
- [ ] Bitcoin [PR#14993](https://github.com/bitcoin/bitcoin/pull/14993), fix data race in `InterruptRPC()`.
- [ ] Bitcoin [PR#14728](https://github.com/bitcoin/bitcoin/pull/14728), fix uninitialized read.
- [ ] Bitcoin [PR#13907](https://github.com/bitcoin/bitcoin/pull/13907), introduce a maximum size for locators.
- [ ] Bitcoin [PR#13808](https://github.com/bitcoin/bitcoin/pull/13808), shuffle coins before grouping, for privacy protection.
- [ ] Bitcoin [PR#13683](https://github.com/bitcoin/bitcoin/pull/13683), avoid potential null pointer dereference.

Some of these issues and PRs are not severe security-related, but backports can avoid the chaos ecosystem of Bitcoin-forked projects and the potential vulnerabilities in the future. 

Reported by `de957ad9679f28a38f02f00cc7928bce8fb424882ff060a3c09c32895b1474cc`.

**Comment by patricklodder** [comment]
Re: last item, "avoid potential null pointer dereference". This is not applicable because the code that could be a null pointer is not part of our code, I'm removing it from the list.

**Comment by patricklodder** [comment]
Status update regarding the items I did not propose fixes for today:

- Item 2, "fix a Char variable used as Bool" can only be done if we upgrade the serialization interfaces. Currently this is unplanned for 1.14, but will be done with 1.21. I propose to consider this fixed with the latter rather than trying to overhaul 1.14 for this.
- Item 3, "improve signrawtransaction error reporting" will have plenty of integration issues - I'd still target 1.14 unless further analysis shows that this is not feasible / worth it. It's only relevant for RPC operations.
- Item 4, "fix crash when disconnecting fail", is easy to fix, but hard to test with our current QA framework, but since this touches validation, I'd still target 1.14
- Item 9, "shuffle coins before grouping, for privacy protection" will have to be done after #2314. I'm still of the opinion we should target 1.21 for this, and no one has said otherwise to date.

**Comment by rnicoll** [comment]
"Bitcoin PR#16251, improve signrawtransacAtion error reporting." I think can't apply to 1.14; if I've read it correctly it's fixing issues with mulisig/partial signing, but the support for those is 1.17+

**Comment by rnicoll** [comment]
https://github.com/dogecoin/dogecoin/pull/2767 work in progress for "fix crash when disconnecting fail"

**Comment by chromatic** [comment]
Agreed with @rnicoll on #16251; getting the tests alone working means backporting a lot of test changes. I'm concerned that'll create a lot of churn in code that's already tricky to integrate.
