### ISSUE TITLE
Tracker for 1.21

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2951]
I'm raising this in an attempt to provide better transparency to the 1.21 development plan and the progress towards it. This is a living plan and can and will change: the current phase scope is mostly fixated, the next phase is a detailed plan, phases after that are in need of further specification and we'll pick those up as we come closer.

### Phase 0: Basic changes ✅

- **Makefile & config rebranding**
- **Basic parametrization**
- **Updates from Bitcoin Core 0.21 minor releases**

### Phase 1: working sync & upgradable from 1.14 🚀

- **Scrypt** ✅
    - #1828
    - #2315
- **Difficulty** ✅
    - Basic #1977
    - Digishield: #1979 
- **AuxPoW** 
    - #2252
    - #2259
    - #2547
    - #2552
    - #2556
    - #2560
    - #2561
    - Accept AuxPoW proofs + built-in miner
    - AuxPoW RPC endpoints
- **Update to bdb 5.3:** #2885 ✅
- **Disable _all_ softforks we don't have on 1.14:**
    - versionbits
    - segwit and protocol dependencies
        - Switch back to legacy addresses: #2274
        - Make sure that segwit activation cannot trigger
        - Disable `NODE_SEGWIT` service to allow sync: #2562
        - Disable `wtxidrelay` support and bring base protocol back to 70015
    - csv
    - taproot
- **Bring back compatibility tests (disabled in: 4eb1be3, 28725808 and a79db04)**

**Done when:**
- [ ] Can be upgraded from existing 1.14 for mainnet and testnet, including wallet
- [ ] Consistently syncs blocks with 1.14 nodes on mainnet, testnet and regtest
- [ ] Can mine new AuxPoW blocks on testnet and regtest that get accepted by 1.14
- [ ] No softforks can trigger on 1.21 that cannot be triggered on 1.14

### Phase 2: Port 1.14 non-ui work forward ⏳
- **Critical 1.14 patches (if still applicable)**
    - Reduce CPU usage during sync (ef9242b9)
    - Increase block download timeouts (a4638bb5, f9b9a591 and 1ec3f19fc)
    - Reduce mempool expiry time (d62033cb)
    - Reduce getheader spam (303be2e)
- **Policy & wallet**
    - Soft & hard dust limit (84157f3df and e83ddb7e)
    - Replace `-discardfeerate` with `-discardthreshold`
    - Adapt to recommended fee & dust defaults (from [doc/fee-recommendation.md](https://github.com/dogecoin/dogecoin/blob/master/doc/fee-recommendation.md))
    - Make sure standard tx match 1.14 completely (from [src/policy/policy.cpp](https://github.com/dogecoin/dogecoin/blob/master/src/policy/policy.cpp#L59)
- **Dogecoin-specific RPC enhancements**
    - `getpeerinfo` additions
    - `generatetoaddress` additions
    - `getnetworkinfo` additions
    - `-rpcnamecoinapi` implementation on auxpow methods
    - `setmaxconnections`
- **Document _all_ API changes inherited from upstream**
- **Make `qa/p2p-policy.py` a compatibility test.**

**Done when:**
- [ ] Dogecoin-specific runtime parametrization is compatible with 1.14
- [ ] 1.21 will not prevent relay of any default 1.14 transaction
- [ ] Defaults implement the fee recommendation
- [ ] All API changes on RPC and REST interfaces are either ported in or differences are documented
- [ ] 1.21 syncs at least as fast as 1.14

### Phase 3: branding, UI and docs ⏳

- Standard branding (replace Bitcoin with Dogecoin in help texts)
- Qt look & feel (logos, icons, wording)
- Backport of all Dogecoin-specific UI enhancements
    - Paper wallet
    - Peer management
    - Key import
    - Tips section
    - Peer dialog enhancements
- Readme
- Installation docs

***At this point, we should have an alpha release***

### At any time, but before beta release ‼️

- Updates to depends packages:
    - expat: #2287
    - libevent: #2288
    - zlib
    - qt
- Port any intrinsics works that makes it out of 1.14 experimental

**Comment by patricklodder** [comment]
> is their a dedicated place where i can send some UI designs as a piece of giving some inspiration or idea's?

I've seen your design in #2948 and it looks clean, but it only makes sense to apply that to a version that is clean too. For 1.21, which I think is a better candidate for a visual redesign than 1.14, I'd recommend to process this later in the 3rd phase, when most functionality is ported. Looking at the work we know of now that needs to be done before that, this is going to be around August/September this year in the best case scenario.

Until then, we can brainstorm and come up with ideas. We could maybe also talk a bit about UX, because most shibes I talk to find the wallet interface quirky. So I'd recommend to give it time, slowly have a discussion about it, and then when the time comes to realize the ideas, we have less discussion 😊

**Comment by alamshafil** [comment]
When Phase 3 is ready, I can help create a custom QT style-sheet based on #2948 for the new UI.

**Comment by victorsk2019** [comment]
HI,

May I ask if the synchronization issue in 1.21 is one which is resulting in error: "prev block not found" in function AcceptBlockHeader()? 

Thanks,
Victor.

**Comment by patricklodder** [comment]
> May I ask if the synchronization issue in 1.21 is one which is resulting in error: "prev block not found" in function AcceptBlockHeader()?

It won't sync fully until auxpow and segwit (and protocol 70016) reversal are done. "prev block not found" can happen when you're getting blocks relayed from the tip right now, because you cannot get to the tip. I'm currently fixing some functional tests for the first auxpow PR, so that both auxpow and pre-auxpow validation gets tested (and automated, so that we don't accidentally fail later on.)

**Comment by victorsk2019** [comment]
Hi,

Regarding this point:
> Can be upgraded from existing 1.14 for mainnet and testnet, including wallet

I've installed 1.21 on top of 1.14 (as a user would) and got this error message when starting dogecoind process:
`[default wallet] Unexpected path index of 0x80000003 (expected 0x80000000 or 0x80000001) for the element at index 1`

Would the problem be with derivation path (in path vector [0', k', i']) having 4th grandchild index (0x80000003) at path[1] used in 1.14 instead of required first or second (expected 0x80000000 or 0x80000001)?  So would the solution be to change derivation path used in 1.14?  Am I getting this right?

Thank you,
Victor.

**Comment by patricklodder** [comment]
@victorsk2019: you are correct, there is still #2355 to merge for that. I will rework that PR. We do need to make sure that wallets created with 1.14.0-1.14.3 (which have the bitcoin SLIP-44 value `0'`) are also recognized.

I added this to the list above, thank you for pointing this out!

**Comment by victorsk2019** [comment]
Hi,

Out of curiosity (and to see how much I remember C++ and learn more Dogecoin Core) I took a look at the derivation path error and it seems that newly created wallets in 1.21 had original derivation path m/0'/0'/i.  Even if I integrated code fragment from https://github.com/dogecoin/dogecoin/pull/2355, I still wasn't getting an error for newly-created wallets (implying that original derivation path was still being used).  I then went ahead and modified DeriveNewChildKey() function and got the error message:

`[MyHDWallet5] Unexpected path index of 0x80000003 (expected 0x80000000 or 0x80000001) for the element at index 1`

meaning that newly-created wallet had desired derivation path m/0'/3'/.  Below is the function I changed:

```
void LegacyScriptPubKeyMan::DeriveNewChildKey(WalletBatch &batch, CKeyMetadata& metadata, CKey& secret, CHDChain& hd_chain, bool internal)
{
    // for now we use a fixed keypath scheme of m/0'/3'/k
    CKey seed;                     //seed (256bit)
    CExtKey masterKey;             //hd master key
    CExtKey accountKey;            //key at m/0'
    CExtKey chainChildKey;         //key at m/0'/3' (external) or m/0'/1' (internal)
    CExtKey childKey;              //key at m/0'/3'/<n>'

    // try to get the seed
    if (!GetKey(hd_chain.seed_id, seed))
        throw std::runtime_error(std::string(__func__) + ": seed not found");

    masterKey.SetSeed(seed.begin(), seed.size());

    // derive m/0'
    // use hardened derivation (child keys >= 0x80000000 are hardened after bip32)
    masterKey.Derive(accountKey, BIP32_HARDENED_KEY_LIMIT);

    // derive m/0'/3' (external chain) OR m/0'/1' (internal chain)
    assert(internal ? m_storage.CanSupportFeature(FEATURE_HD_SPLIT) : true);
    accountKey.Derive(chainChildKey, BIP32_HARDENED_KEY_LIMIT+(internal ? 1 : 3));

    // derive child key at next index, skip keys already known to the wallet
    do {
        // always derive hardened keys
        // childIndex | BIP32_HARDENED_KEY_LIMIT = derive childIndex in hardened child-index-range
        // example: 1 | BIP32_HARDENED_KEY_LIMIT == 0x80000001 == 2147483649
        if (internal) {
            chainChildKey.Derive(childKey, hd_chain.nInternalChainCounter | BIP32_HARDENED_KEY_LIMIT);
            metadata.hdKeypath = "m/0'/1'/" + ToString(hd_chain.nInternalChainCounter) + "'";
            metadata.key_origin.path.push_back(0 | BIP32_HARDENED_KEY_LIMIT);
            metadata.key_origin.path.push_back(1 | BIP32_HARDENED_KEY_LIMIT);
            metadata.key_origin.path.push_back(hd_chain.nInternalChainCounter | BIP32_HARDENED_KEY_LIMIT);
            hd_chain.nInternalChainCounter++;
        }
        else {
            chainChildKey.Derive(childKey, hd_chain.nExternalChainCounter | BIP32_HARDENED_KEY_LIMIT);
            metadata.hdKeypath = "m/0'/3'/" + ToString(hd_chain.nExternalChainCounter) + "'";
            metadata.key_origin.path.push_back(0 | BIP32_HARDENED_KEY_LIMIT);
            metadata.key_origin.path.push_back(3 | BIP32_HARDENED_KEY_LIMIT);
            metadata.key_origin.path.push_back(hd_chain.nExternalChainCounter | BIP32_HARDENED_KEY_LIMIT);
            hd_chain.nExternalChainCounter++;
        }
    } while (HaveKey(childKey.key.GetPubKey().GetID()));
    secret = childKey.key;
    metadata.hd_seed_id = hd_chain.seed_id;
    CKeyID master_id = masterKey.key.GetPubKey().GetID();
    std::copy(master_id.begin(), master_id.begin() + 4, metadata.key_origin.fingerprint);
    metadata.has_key_origin = true;
    // update the chain model in the database
    if (hd_chain.seed_id == m_hd_chain.seed_id && !batch.WriteHDChain(hd_chain))
        throw std::runtime_error(std::string(__func__) + ": writing HD chain model failed");
}```

Is this something I should submit as a PR?

Thank you,
Victor.

**Comment by patricklodder** [comment]
@victorsk2019 feel free to submit PR. Note that we need to support both '3 and '0 as BIP44 coin field value for this, because wallets created with 1.14.0-1.14.4 have `0'` for mainnet:

| versions | coin in derivation path | why |
| --- | ---: | ---|
| 1.10.0 and below | none | HD not supported |
| 1.14.0-1.14.4 | `0'` | missed with 1.14.0 porting |
| 1.14.5 and up | `3'` | corrected with #2490 |
| 1.21.0 (future) | `3'` | to be implemented |

**Comment by victorsk2019** [comment]
Hi,

Pardon my ignorance, but what do you mean by:

> auxpow and segwit (and protocol 70016) reversal are done

I've read this discussion https://github.com/dogecoin/dogecoin/discussions/2264 and for what its worth agree that implementing Segwit in 1.21 is a good idea because it helps avoid malleability issues (which is a known problem in cryptography).  Apparently, bitcoin people have already given this issue some thought and came up with separating signatures from transaction data as the only practical solution.  As such, porting this implementation into Dogecoin Core 1.21 should make it more secure.  

It would be really great if 1.21 could be made to synchronize.  Can synchronization issue be fixed programmatically or are there some external factors involved?

Thank you,
Victor.

**Comment by patricklodder** [comment]
I mean with that that we (a) have merged auxpow functionality (2 PRs) and (b) have made absolutely sure that segwit and wtxid-based relay are disabled.

**Re: to segwit or not segwit.**

For now, segwit would better be disabled. With 1.14.0, the soft fork  introduced an averse effect that removed about 8% of transactions from the network and ultimately lead to all these issues we had with fee/dust policy. So we have to be extremely careful and not try to do too many changes at once. 

Therefore, the plan has for a while now been to just release 1.21 fully protocol-compliant with 1.14 - which is reflected in the plan above - and after that we can work on any protocol extensions on a 1.21.1 or .2 or .3... Segwit has become a bit controversial in that entire discussion thread too, so let's revive that discussion when we're a little closer to being done with 1.21.0.

**Re: get it to sync**

We'll get 1.21 to sync for sure. Just need to take care of inconsistencies so that the function/quality gates under "done when" can be met. For now, we'll need your #2977 to get in, and I am working on a regtest parametrization fix because there's a chainparams discrepancy between Ross' tag in his repo, and the code merged here so far (on signet, but that laid bare a problem with regtest.)

**Comment by patricklodder** [comment]
It's not just lightning that is affected by it. Anyone's ability to change an announced transaction's hash is risky because that hash is recorded as input for a followup transaction. It's a structural problem and it must be solved.

I don't think the question is **if**; rather **how**. There's benefits to copying Bitcoin's solution and there are benefits not to copy it. We just have to have the discussion, but now is not the time.

**Comment by victorsk2019** [comment]
Hi,

Quick note: I was able to synchronize 1.21 fully on testnet.  This was for my personal satisfaction to get it working, learn how it works and for fun too 😊  I did it without the weird version changes I mentioned earlier - it's mostly the addition of one function, really.  This PR helped a lot: https://github.com/dogecoin/dogecoin/pull/2562, but I am changing value of `MSG_WITNESS_FLAG` and `NODE_WITNESS` my way because `MSG_WITNESS_FLAG` is used elsewhere and I think it is safer to set them to all 0's.

In my test, I created 2 testnet wallets, one with 100 DOGE and sending and receiving seems to be working (see below) (though I was getting "Fee Estimation" error).

![image](https://user-images.githubusercontent.com/47955466/178076124-592db62d-d78e-4065-88b7-375cd9f39458.png)

![image](https://user-images.githubusercontent.com/47955466/178076150-e55104a4-e9f4-4ad4-90a9-27039fca0110.png)

It's kind of too bat that GetConsensus() in 1.21 is not recursive like in 1.14 and chain parameters and not represented in BST so as to retrieve chain parameter category using GetConsensus() - I think that's pretty cool.  Will there be any adverse effects on the network if I try to synch 1.21 with mainnet?

**Comment by patricklodder** [comment]
> It's kind of too bad that GetConsensus() in 1.21 is not recursive like in 1.14 and chain parameters are not represented in BST so as to retrieve chain parameter category using GetConsensus() - I think that's pretty cool.

I asked Ross about it (he's the original author of the tree structure) a couple of times but it looks like this didn't make it in.

If we're going to do a form of fork management (I agree we should), realize that Bitcoin Core did a refactor on the soft fork side for 22.0, to improve how this works for softforks:

See https://github.com/bitcoin/bitcoin/commit/2b0d291da8f479739ff394dd92801da8c40b9f8e

I think that it can be beneficial to have a uniform solution for this, maybe we can make something out of this that works for our 2 hardforks too?

**Comment by victorsk2019** [comment]
Well, it is always a pleasure to see practical applications of algorithm analysis courses I studied in school 😃.  As I understand it, the original implementation of GetConsensus() is using BFS to traverse BST to retrieve chain parameter category - pretty neat.  But, from what I've seen, 1.21 seems to be slightly more time/memory efficient as it picks chain parameter with O(1) efficiency.  But it depends if you want to integrate consensus categories from (now) 1.14.6.

P.S. I didn't do a PR with functional synchronization implementation for 1.21 because from what I understand now it is probably too early to integrate this functionality at this point, even though there are a only a few changes.

**Comment by patricklodder** [comment]
> 1.21 seems to be slightly more time/memory efficient as it picks chain parameter with O(1) efficiency.

This is at the cost of parametrized activation as a boolean and instead using an int. It's ok, we can do that, it's just a big change from a perspective of fork management. My point is that if we're going to change it, I think we should change it into something good - if this is good, then fine. But we should put some thought to it because I haven't seen any argument to leaving it out. Doesn't have to be a long discussion either.

>  I didn't do a PR with functional synchronization implementation for 1.21

Let's finish #2977 and then I'd be happy to review any work you want to pull on 1.21-dev. It's better to collaborate on this than just have one person pushing, so by all means, submit all the PRs: it's much appreciated ❤️

**Comment by patricklodder** [comment]
_Re: regtest parametrization in 1.21 comment by @victorsk2019 in https://github.com/dogecoin/dogecoin/pull/2977#issuecomment-1264730855_

Regtest needs to be fully re-engineered to be compatible with 1.14 and I am working on it - for weeks now. I'd not recommend spending any time on it at this time, because the entire test suite fails incrementally with each parameter harmonization. I am simply looking to make the whole work by letting the tests tell me what failed, solve and document rationale one-at-a-time, and then reorganize all changes into digestible sets that make sense - and PR that last result.

I was targeting to propose the fixes **after we have working sync** without the backward regtest compatibility, because until then we cannot fully test against 1.14 behavior anyway.

**Comment by huangkaoya** [comment]
How is it going？

**Comment by Akashshike** [comment]
@
