### ISSUE TITLE
The "making 1.21-dev great again" plan

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3349]
Currently there are several issues with the `1.21-dev` branch that block the CI and other testing efforts:

1. The macOs Native CI job needs to be converted to arm64 because Cirrus no longer supports Intel Mac native builds - reported [here](https://github.com/dogecoin/dogecoin/pull/3260#issuecomment-1573142223)
2. Newer boost versions cause several issues on x86_64 linux and ARM macOS reported [here](https://github.com/dogecoin/dogecoin/pull/3128#issuecomment-1407770481) and [here](https://github.com/dogecoin/dogecoin/pull/3260#issuecomment-1750836873) 
3. The `crc32c` subtree needs updating to support non-linux ARM, reported [here](https://github.com/dogecoin/dogecoin/pull/3260#issuecomment-1573142223)
4. Porting #3308 will fix bdb5 inclusion for mac in the same way it did for 1.14.7-dev
5. secp256k1 subtree needs an update because that has evolved to be more stable now, and I've seen the occasional unit test error in the wild on the current bitcoin-core/secp256k1@3967d96 we have
6. `contrib/devtools/security-check.py` does not support `arm64-darwin`, reported [here](https://github.com/dogecoin/dogecoin/pull/3260/files#diff-8b65cb9698a57b79410c04b8cfc884ff6b0fa2bca66804596626bf2cdfa10401R25-R28)

Because at least 1, 2 and 3 needs to be done to get a working macOS native CI, I think we should just disable that CI job for the initial steps of... 

### ... the plan

- [x] 1. Disable macOS Native CI - #3350
- [ ] 2a. Update `crc32c` subtree to bitcoin-core/crc32c-subtree@0bac72c4 - #3374
- [x] 2b. Cherry-pick a32eb262 from 1.14.7-dev and fix configure.ac brew bdb selection - #3375
- [x] 2c. Cherry-pick bitcoin/bitcoin@058eb69 to fix boost 1.82 compatibility - #3376
- [ ] 3. Enable macOS Native CI as an arm64 host
- [ ] 4a. Update the boost pinned dependency to 1.82
- [ ] 4b. Update secp256k1 to [v0.4.0](https://github.com/bitcoin-core/secp256k1/blob/master/CHANGELOG.md#040---2023-09-04) (because this has a windows symbol fix that will be important later on)
- [ ] 4c. Update devtools checks (security, symbols) to support `arm64-darwin`.

Please let me know if there are any objections to this plan.

**Comment by c5245010** [comment]
hey Pat,
I am just wondering if possible dogecoin could replica EIP-4844 (sharding) as TPS enhancement in the future plan?

**Comment by patricklodder** [comment]
Not in that exact form (we have Bitcoin script, not EVM) but you can probably hack together optimistic rollups today (but I wouldn't recommend it, it will be very hard to do securely.) However, if the Dogecoin network wants to adopt taproot at some point, things like [TapRet](https://standards.lnp-bp.org/commitment-schemes/lnpbp-0012) and [BitVM](https://bitvm.org/bitvm.pdf) will become possible, permissionlessly. And people have only just started to look at the potential application of rollups using taproot - it's an interesting space to watch right now.

**Comment by c5245010** [comment]
> Not in that exact form (we have Bitcoin script, not EVM) but you can probably hack together optimistic rollups today (but I wouldn't recommend it, it will be very hard to do securely.) However, if the Dogecoin network wants to adopt taproot at some point, things like [TapRet](https://standards.lnp-bp.org/commitment-schemes/lnpbp-0012) and [BitVM](https://bitvm.org/bitvm.pdf) will become possible, permissionlessly. And people have only just started to look at the potential application of rollups using taproot - it's an interesting space to watch right now.

BitVM is an interesting topic and dogecoin networks would explode if that being implement.
I am not sure what X is doing right now, ppl discuss a lot X will onboard doge later.
In your opinion, how does dogecoin network react later?

**Comment by patricklodder** [comment]
> What are the main goals of 1.21?

The goal is updating the codebase safely to a point where we can propose protocol improvements without being scared of unforeseen consequences, like happened with 1.14's CLTV softfork. Basically, creating a baseline from which we can work linearly from there on out. 

> Are we going to have SegWit addresses and CSV op code?

1.21.0 should prepare for at least CSV and hopefully segwit in a slightly modified/optimized form, but do note that in earlier discussions, devs agreed that actually proposing activation for these should be done in a follow-up release, making sure that we have a 1-on-1 compatibility with the current protocol first, as the 1.21 code has significantly evolved vs 1.14. I also think today that doing this is the way to go, but am happy to [discuss](https://github.com/dogecoin/dogecoin/discussions) if anyone has a different opinion.
