### ISSUE TITLE
Estimate(smart)fee fixes tracker

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3440]
I made a new tracker because the original issue (#3385) was fixed with the merge of (#3389), and this will now cross release lines:

- [x] A new default configuration that makes `estimatefee` and `estimatesmartfee` functional, also in periods of spam - #3389
- [ ] Detect and ignore when an old version of fee estimates is available in the datadir - #3433  
- [ ] A facility for users to configure this functionality to their liking, because developers should not dictate the fee a user pays.
- [ ] Expansive documentation to using smartfees, because using this facility (or any other fee estimation facility) does not come without caveats and risk.

**Comment by georgeartem** [comment]
Where in this are you drawing the line for 1.14.7 vs. next planned?

**Comment by patricklodder** [comment]
If #3433 can get in, would be good, because saves manual intervention for operators. It's basically a tiny version of what is needed for the 3rd item. If not possible, then we can opt to skip that PR.

So the line is either in the middle, or before #3433.
